version: "3.8"

services:

  db:
    image: postgres
    env_file:
      - server/.env

  web:
    build: .
    command: "tail -f /dev/null"
    env_file:
      - server/.env
    volumes:
      - .:/application
    ports:
      - "8000:8000"
      - "5000:5000"
    depends_on:
      - db
